### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by MatteDAnna** [hatfieldm48/sports_animation#1]
I feel like I have followed all the steps, but when I try to run the code I get this error:
[errors.pdf](https://github.com/hatfieldm48/sports_animation/files/5416168/errors.pdf)

**Comment by hatfieldm48** [comment]
Arvendui, sorry about the issues. Based on that error, it looks like there might be a disconnect between what the code is expecting for the data directory organization and the setup you're working with. Frist, do you mind running `app.py` from within the same directory that app.py resides? This is coded assuming it's run from the same directory, and I didn't build in any code to correct for that yet. If that doesn't solve the issue though, do you mind sending over the following items:

1) Confirm you pulled the big_data_bowl_2021 branch
2) Are you running this on a windows or mac computer?
3) The value you set for `data_file_path` in line 10 of app.py
4) A brief outline of what your weekN directory looks like. For example mine is as follows:

- big_data_bowl_2021/
    - week1/
        - 2018090600_75.csv
        - ...
    - week2/
    - ...
    - week17/
    - games.csv
    - players.csv
    - plays.csv

**Comment by hatfieldm48** [comment]
No other updates here, so I'm going to close this issue for now
